### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by belv2c** [cremalab/crema-components#23]

**Comment by roblafeve** [comment]
@belv2c it could be neat to use the issue as a place for planning out the public API of components/discuss approach. Just an idea, though! 🤷

**Comment by belv2c** [comment]
@roblafeve do you mean using this space as a place to document how we're planning to build out the component?

**Comment by roblafeve** [comment]
@belv2c yeah, that's what I was envisioning 😄

**Comment by roblafeve** [comment]
👋 Thought I'd move some conversation here. I think it would be helpful to decide on the interface for this module. I think the two options we have are:

```typescript
<Breadcrumbs links={} />
```

**Comment by roblafeve** [comment]
👋 Thought I'd move some conversation here. I think it would be helpful to decide on the interface for this module. I think we have two options—a configuration vs composition-based approach. In this case, I lean toward Option A.

## Option A - Configuration-Based

Pros:
- Simplicity, I only need to interact with a single component
- Since links will be dynamic, sticking with an array may be easier—we'll need to be manipulating this array in either case

Cons:
- I can't think of any, honestly

```tsx
const links: BreadcrumbLinks = [
  { href: "#", label: "A" },
  { href: "#", label: "B" },
  { href: "#", label: "C" },
]

<Breadcrumbs links={links} />
```

## Option B - Composition-Based

Pros:
- I honestly can't think of any

Cons:
- I have to import two components
- I have to manually map over `links`

```tsx
const links: BreadcrumbLinks = [
  { href: "#", label: "A" },
  { href: "#", label: "B" },
  { href: "#", label: "C" },
]

<Breadcrumbs links={links}>
  {links.map((link) => (
    <BreadcrumbItem key={link.label} {...link} />
  ))}
</Breadcrumbs>
```
